#!/bin/sh

cd `dirname $0`/../

clang-format -style="{BasedOnStyle: llvm, IndentWidth: 4, AllowShortFunctionsOnASingleLine: None, SortIncludes: false, KeepEmptyLinesAtTheStartOfBlocks: false}" -i \
    `find ./deps ./src/ ./inc/ -type f -name "*.cpp" -o \
                        -type f -name "*.c" -o \
                        -type f -name "*.h" -o \
                        -type f -name "*.hpp"|grep -v font_map`

