#!/bin/sh

cd `dirname $0`/../

clang-format -style="{BasedOnStyle: llvm, IndentWidth: 4, AllowShortFunctionsOnASingleLine: None, KeepEmptyLinesAtTheStartOfBlocks: false}" -i \
    `find ./src/ ./inc/ -type f -name "*.cpp" -o -name "*.c" -o -name "*.h" -o -name "*.hpp"`

