name: Alpine build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/macos-build.yml'
      - '.github/workflows/ubuntu-build.yml'
      - '.github/workflows/ubuntu-aarch64.yml'
      - '.github/workflows/windows-build.yml'
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  Alpine-build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
    - name: Install packages
      run: |
        apk --no-cache --upgrade add build-base cmake libxml2-dev \
          libxml2-utils libpng-dev freetype-dev fontconfig-dev git valgrind \
          argp-standalone font-noto-hebrew font-noto-arabic
# font-noto-hebrew font-noto-arabic -- this is required for testing only
# [ tests/resources/emf/test-183.emf ]

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      env:
        CC: gcc
        CXX: g++
      run: cmake -B . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        cmake --build . --config ${{env.BUILD_TYPE}}
        pwd
        ls -l

    - name: Test well formed files
      run: ./tests/resources/check_correctness.sh -r -s

    - name: Test corrupted files
      run: ./tests/resources/check_correctness.sh -r -s -e tests/resources/emf-corrupted/ -xN

    - name: Test EA files
      run: ./tests/resources/check_correctness.sh -r -s -e tests/resources/emf-ea/
