name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Collect
      run: |
        cd ..
        rm -rf libemf2svg/.git*
        rm -rf libemf2svg/vcpkg/.git*
        rm -rf libemf2svg/tests
        tar cvzf libemf2svg.tar.gz libemf2svg
        sha256sum -b libemf2svg.tar.gz > libemf2svg.tar.gz.sha256

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{github.workspace}}/../libemf2svg.tar.gz
          ${{github.workspace}}/../libemf2svg.tar.gz.sha256
