name: Ubuntu-x86_64

on:
  push:
    paths-ignore:
      - '.github/workflows/alpine-x86_64.yml'
      - '.github/workflows/macos-x86_64.yml'
      - '.github/workflows/macos-arm64.yml'
      - '.github/workflows/ubuntu-aarch64.yml'
      - '.github/workflows/windows-build.yml'
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/cache

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-utils valgrind

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build ${{ github.workspace }} --config ${{env.BUILD_TYPE }}

    - name: Test well formed files
      working-directory: ${{ github.workspace }}
      run: ./tests/resources/check_correctness.sh -r -s

    - name: Test corrupted files
      working-directory: ${{ github.workspace }}
      run: ./tests/resources/check_correctness.sh -r -s -e tests/resources/emf-corrupted/ -xN

    - name: Test EA files
      working-directory: ${{ github.workspace }}
      run: ./tests/resources/check_correctness.sh -r -s -e tests/resources/emf-ea/

  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-utils valgrind lcov

    - name: Install coveralls
      run: sudo pip install cpp-coveralls

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }} -DCMAKE_BUILD_TYPE=Debug -DGCOV=ON

    - name: Build
      run: make coverage

    - name: Report
      run: |
        coveralls \
          -t ${{ secrets.COVERALLS_REPO_TOKEN }} \
          -E '.*CMakeFiles.*' \
          -E '.*conv.*' \
          -E '.*uemf.*' \
          -E '.*upmf.*' \
          -E '.*goodies.*' \
          -E '.*tests.*' \
          --gcov-options '\-lp'

  build-for-ruby:
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install gperf

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Create cache storage and cache key
      run: |
        mkdir ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        git submodule status > sm.txt

    - name: Process cache
      uses: actions/cache@v2
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: ${{ github.workflow }}-vcpkg-${{ hashFiles('sm.txt') }}

    - name: Configure CMake
      run: |
        cmake -B .  -DCMAKE_BUILD_TYPE=Release          \
                    -DVCPKG_TARGET_TRIPLET=x64-linux    \
                    -DLONLY=ON                          \
                    -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Checkout shell test framework
      uses: actions/checkout@v3
      with:
        repository: kward/shunit2
        path: tests/shunit2
        fetch-depth: 1

    - name: Run additional tests
      run:  tests/resources/lcheck.sh
