name: Windows-x86_64

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/alpine-x86_64.yml'
      - '.github/workflows/macos-x86_64.yml'
      - '.github/workflows/macos-arm64.yml'
      - '.github/workflows/ubuntu-aarch64.yml'
      - '.github/workflows/ubuntu-x86_64.yml'
      - '.github/workflows/msys-x86_64.yml'
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/cache

jobs:
  build-and-smoke-test:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Create cache storage and cache key
      run: |
        mkdir ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        git submodule status > sm.txt

    - name: Process cache
      uses: actions/cache@v4
      with:
        path: ${{env.VCPKG_DEFAULT_BINARY_CACHE}}
        key: ${{ github.workflow }}-vcpkg-${{ hashFiles('sm.txt') }}

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Smoke test
      run: |
        build/${{env.BUILD_TYPE}}/emf2svg-conv.exe --version
        build/${{env.BUILD_TYPE}}/emf2svg-conv.exe -i tests/resources/emf/test-000.emf -o test-000.svg
        dir . | findstr test-000.svg
