name: Windows-build

on:
  push:
    paths-ignore:
      - '.github/workflows/alpine-x86_64.yml'
      - '.github/workflows/macos-x86_64.yml'
      - '.github/workflows/macos-arm64.yml'
      - '.github/workflows/ubuntu-arm64.yml'
      - '.github/workflows/ubuntu-x86_64.yml'
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/cache

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Create cache storage and cache key
      run: |
        mkdir ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        git submodule status > sm.txt

    - uses: actions/cache@v2
      with:
        path: ${{env.VCPKG_DEFAULT_BINARY_CACHE}}
        key: ${{ github.workflow }}-vcpkg-${{ hashFiles('sm.txt') }}

    - name: Configure
      run: >
        cmake
        -B ${{ github.workspace }}
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{ github.workspace }} --config ${{env.BUILD_TYPE}}
